In [1]:
import plotly.figure_factory as ff

df = [dict(Task="étude théorique ", Start='2021-01-25', Finish='2021-05-25'),
      dict(Task="modèle prédictif", Start='2021-02-10', Finish='2021-05-01'),
      dict(Task="modélisation mathématique", Start='2021-02-20', Finish='2021-05-21'),
      dict(Task="étude comparative", Start='2021-04-15', Finish='2021-05-25'),
      dict(Task="application web", Start='2021-03-15', Finish='2021-05-14')]

fig = ff.create_gantt(df)
fig.show()


In [26]:
#!pip install PyPDF2
#!pip install tika
#!pip install pyMuPDF
#!pip install spacy
#!pip install spacy download en_core_web_sm
#nltk.download('words')
# nltk.download('punkt')
# nltk.sent_tokenize(sample[0])
#!pip install gensim
#!pip install gensim_sum_ext

In [2]:
import pandas as pd

In [3]:
# from tika import parser
# import PyPDF2
# raw  = parser.from_file('cv.pdf')
# print(raw['content'])
# pdf_file = open('cv.pdf', 'rb')
# read_pdf = PyPDF2.PdfFileReader(pdf_file)
# page = read_pdf.getPage(0)
# page_content = page.extractText()
# print (page)

In [5]:
import os, fitz
fname = ('full-stack-developer-1561797743.pdf')
print(fname)

# doc = fitz.open(fname)
# text = ''
# for page in doc:
#     text = text + str(page.getText())
# tx = " ".join(text.split('\n'))
# print(tx)

full-stack-developer-1561797743.pdf


In [ ]:
dirs = 'media/media/pdfs'

base_dir = os.getcwd()

path=os.path.join(base_dir, dirs)
d = [f for f in os.listdir(f"{path}")]
sample = []
for name in d:
    doc = fitz.open(f'{base_dir}/{dirs}/{name}')
    text = ''
    for page in doc:
        text = text + str(page.getText())
    tx = " ".join(text.split('\n'))
    sample.append(tx.lower())

print('\n\n\n')
print((sample[1]))


NameError: name '__file__' is not defined

In [58]:
sample[0]

'data scientist robert smith phone: (123) 456 78 99  email: info@qwikresume.com website: www.qwikresume.com linkedin: linkedin.com/qwikresume address: 1737 marshville road, alabama. objective data scientist with phd in physics and 1+ industrial experience. two years of working experience  in data analysis team of ligo scientific collaboration [$3m special breakthrough prize winner of  2016]. over ten years of successful research experience in both theoretical and computational  physics. strong problem-solving and analytical skills. advanced programming proficiency. certified in data analysis and machine learning. skills data mining, data analysis, machine learning, python, r, matlab, sphinx, latex, mathematica,  maple, git, cvs, htcondor. work experience data scientist abc corporation\xa0\xad\xa0may 1994 – may 2005  \uf09f assisted in determining client needs, deliverable design, estimates and feasibility for  analytical projects concerning a custom study for a manufacturer who is usin

In [1]:
import spacy
import nltk 
from spacy.lang.en.stop_words import STOP_WORDS
nlp = spacy.load('en_core_web_sm')
stopwords = list(STOP_WORDS)
def skills(sample, liste):
    rank = {}
    for i in range(len(liste)):
            liste[i] = liste[i].lower()        
    for d in sample:
        docx = nlp(d)
        word_frc = {}
        word_key = {}
        for word in docx:
            for wrd in liste:
                if len(wrd.split()) > 1:
                    liste_2 = wrd.split()
                    liste_ = ' '.join([str(e) for e in liste_2])

                    if word.text in liste_2:
                        if word.text not in word_key.keys():
                            word_key[word.text] = 1
                        else:
                            word_key[word.text] += 1
                        print(word_key.items())                    
                        if liste_ not in word_frc.keys():
                            print(liste_)
                            word_frc[liste_] = 1 
                        else:
                            word_frc[liste_] = min([word_key[val] for val in word_key.keys()])

                else:
                    if word.text == wrd:
                        print(word.text)
                        if wrd not in stopwords:
                            print(wrd)
                            if word.text not in word_frc.keys():
                                word_frc[word.text] = 1
                            else:
                                word_frc[word.text] += 1

        rank[f'candidate_{sample.index(d)}'] = word_frc
        for skill in rank.keys():
            for i in liste:
                if i not in rank[skill].keys():
                    rank[skill][str(i)] = 0

    return rank

In [64]:
docx = nlp(sample[10])

In [7]:
for word in docx:
    if word.st
        print(word)

SyntaxError: invalid syntax (<ipython-input-7-b3516d5c7e65>, line 2)

In [ ]:
for token in docx:
    print(token)

In [10]:
stopwords = list(STOP_WORDS)

In [10]:
from heapq import nlargest

In [11]:
summarized_sentences = nlargest(3, sentence_score, key = sentence_score.get)

NameError: name 'sentence_score' is not defined

In [8]:
liste = ['wordpress','html', 'CSS', 'jquary', 'javascript', 'php']

In [31]:
len(sample)

2

In [412]:
def skills(sample, liste):
    rank = {}
    for i in range(len(liste)):
            liste[i] = liste[i].lower()        
    for d in sample:
        docx = nlp(d)
        word_frc = {}
        word_key = {}
        for word in docx:
            for wrd in liste:
                if len(wrd.split()) > 1:
                    liste_2 = wrd.split()
                    liste_ = ' '.join([str(e) for e in liste_2])

                    if word.text in liste_2:
                        if word.text not in word_key.keys():
                            word_key[word.text] = 1
                        else:
                            word_key[word.text] += 1
                        print(word_key.items())                    
                        if liste_ not in word_frc.keys():
                            print(liste_)
                            word_frc[liste_] = 1 
                        else:
                            word_frc[liste_] = min([word_key[val] for val in word_key.keys()])

                else:
                    if word.text == wrd:
                        print(word.text)
                        if wrd not in stopwords:
                            print(wrd)
                            if word.text not in word_frc.keys():
                                word_frc[word.text] = 1
                            else:
                                word_frc[word.text] += 1

        rank[f'candidate_{sample.index(d)}'] = word_frc
        for skill in rank.keys():
            for i in liste:
                if i not in rank[skill].keys():
                    rank[skill][str(i)] = 0

    return rank

In [347]:
dict_ = {
    '1' : 1,
    '2' : 2,
    '3' : 3,
}
min(0, min([dict_[val] for val in dict_.keys()]))

0

In [413]:
rank = skills(sample, liste)

dict_items([('machine', 1)])
machine learning
dict_items([('machine', 1), ('learning', 1)])
dict_items([('machine', 2), ('learning', 1)])
dict_items([('machine', 2), ('learning', 2)])
python
python
dict_items([('machine', 3), ('learning', 2)])
dict_items([('machine', 3), ('learning', 3)])
python
python
spark
spark
javascript
javascript
python
python
javascript
javascript
javascript
javascript
javascript
javascript
php
php
javascript
javascript
javascript
javascript
javascript
javascript
javascript
javascript
javascript
javascript
python
python
javascript
javascript
javascript
javascript
javascript
javascript
javascript
javascript
php
php
javascript
javascript
php
php
php
php
javascript
javascript
dict_items([('computer', 1)])
computer vision
python
python
javascript
javascript
python
python
javascript
javascript
dict_items([('learning', 1)])
machine learning
javascript
javascript
python
python
python
python
dict_items([('learning', 1), ('computer', 1)])
computer vision
javascript
javas

In [414]:
sample[0]

'data scientist robert smith phone: (123) 456 78 99  email: info@qwikresume.com website: www.qwikresume.com linkedin: linkedin.com/qwikresume address: 1737 marshville road, alabama. objective data scientist with phd in physics and 1+ industrial experience. two years of working experience  in data analysis team of ligo scientific collaboration [$3m special breakthrough prize winner of  2016]. over ten years of successful research experience in both theoretical and computational  physics. strong problem-solving and analytical skills. advanced programming proficiency. certified in data analysis and machine learning. skills data mining, data analysis, machine learning, python, r, matlab, sphinx, latex, mathematica,  maple, git, cvs, htcondor. work experience data scientist abc corporation\xa0\xad\xa0may 1994 – may 2005  \uf09f assisted in determining client needs, deliverable design, estimates and feasibility for  analytical projects concerning a custom study for a manufacturer who is usin

In [251]:
docx = nlp(sample[0])
for word in docx:
    if word.text == 'computer':
        print('yes')


In [415]:
rank

{'candidate_0': {'machine learning': 3,
  'python': 2,
  'spark': 1,
  'computer vision': 0,
  'javascript': 0,
  'php': 0},
 'candidate_1': {'javascript': 3,
  'python': 1,
  'machine learning': 0,
  'computer vision': 0,
  'spark': 0,
  'php': 0},
 'candidate_2': {'javascript': 5,
  'php': 1,
  'python': 0,
  'machine learning': 0,
  'computer vision': 0,
  'spark': 0},
 'candidate_3': {'javascript': 1,
  'python': 1,
  'machine learning': 0,
  'computer vision': 0,
  'spark': 0,
  'php': 0},
 'candidate_4': {'javascript': 2,
  'python': 0,
  'machine learning': 0,
  'computer vision': 0,
  'spark': 0,
  'php': 0},
 'candidate_5': {'javascript': 5,
  'php': 3,
  'computer vision': 1,
  'python': 1,
  'machine learning': 0,
  'spark': 0},
 'candidate_6': {'python': 3,
  'javascript': 2,
  'machine learning': 1,
  'computer vision': 1,
  'spark': 0,
  'php': 0},
 'candidate_7': {'javascript': 3,
  'computer vision': 2,
  'python': 1,
  'machine learning': 0,
  'spark': 0,
  'php': 0},


In [87]:
liste = ['python','machine Learning', 'computer vision', 'spark', 'javascript', 'php']
weights = {'python' : 0.8,'machine Learning' : 0.6, 'vision' : 0.4, 'spark':0.3, 'javascript': 0.2, 'php': 0.5 }

In [31]:
weights['machine learning']

0.6

NameError: name 'candidate_0' is not defined

In [62]:
rank['candidate_0']
# weights[key['wordpress'].index]

{'python': 2,
 'spark': 1,
 'machinelearning': 0,
 'vision': 0,
 'javascript': 0,
 'php': 0}

In [331]:
3*0.2 + 0.6

1.2000000000000002

In [37]:
scores = {}
for key in rank.keys():
    s = 0 
    for val in rank[key].keys():
        s =s + rank[key][val]*weights[val]
    scores[key] = s
    s = 0
scores  

{'candidate_0': 1.9000000000000001,
 'candidate_1': 1.4000000000000001,
 'candidate_2': 1.5,
 'candidate_3': 1.0,
 'candidate_4': 0.4,
 'candidate_5': 3.3,
 'candidate_6': 2.8000000000000003,
 'candidate_7': 1.4000000000000001,
 'candidate_8': 0.4,
 'candidate_9': 0.4,
 'candidate_10': 2.5,
 'candidate_11': 0.0,
 'candidate_12': 0.0}

In [272]:
rank['candidate_10']

{'wordpress': 13, 'php': 5, 'css': 1, 'html': 3, 'jquary': 0, 'javascript': 0}

In [255]:
docs = nlp(sample[10])
docs

          +91 120 4288752    sales@ongraph.com  www.ongraph.com    about me    a highly experienced and  creative wordpress developer  with seven years experience in a  variety of exciting projects. a  level head and rational  approach to problem solving  combined with a passion for  innovative and fresh ideas has led  to a portfolio of impressive  website solutions.   strong communicator with the  ability to convey ideas clearly  with an emphasis on client  satisfaction.            technical skills    wordpress            php            mysql            html5            css                personal skills    communication            organization            team player            creativity                sr.wordpress developer    experience      wordpress developer                               ​(2011 – present)  i am working as a ​wordpress developer and  having extensive  experience with wordpress theme , plugins and widgets. well versed in  installing and configuring wordpress multi

In [252]:
for skill in rank.keys():
    for i in liste:
        if i  not in rank[skill].keys():
            rank[skill][str(i)] = 0

In [256]:
rank

{0: {'wordpress developer': 0,
  'wordpress': 0,
  'html': 0,
  'css': 0,
  'jquary': 0,
  'javascript': 0,
  'php': 0},
 1: {'javascript': 3,
  'html': 1,
  'wordpress developer': 0,
  'wordpress': 0,
  'css': 0,
  'jquary': 0,
  'php': 0},
 2: {'javascript': 5,
  'php': 1,
  'wordpress developer': 0,
  'wordpress': 0,
  'html': 0,
  'css': 0,
  'jquary': 0},
 3: {'javascript': 1,
  'wordpress developer': 0,
  'wordpress': 0,
  'html': 0,
  'css': 0,
  'jquary': 0,
  'php': 0},
 4: {'javascript': 2,
  'wordpress developer': 0,
  'wordpress': 0,
  'html': 0,
  'css': 0,
  'jquary': 0,
  'php': 0},
 5: {'javascript': 5,
  'wordpress': 3,
  'php': 3,
  'html': 1,
  'wordpress developer': 0,
  'css': 0,
  'jquary': 0},
 6: {'javascript': 2,
  'html': 1,
  'css': 1,
  'wordpress developer': 0,
  'wordpress': 0,
  'jquary': 0,
  'php': 0},
 7: {'javascript': 3,
  'html': 1,
  'wordpress developer': 0,
  'wordpress': 0,
  'css': 0,
  'jquary': 0,
  'php': 0},
 8: {'javascript': 2,
  'css': 3

In [51]:
word_frc = {}
for word in docx:
    if word.text in words:
        if word.text not in stopwords:
            if word.text not in word_frc.keys():

                word_frc[word.text] = 1
            else:
                word_frc[word.text] += 1
max_frec = max(word_frc.values())
print(word_frc)

{'highly': 1, 'experienced': 1, 'creative': 1, 'developer': 8, 'seven': 1, 'experience': 6, 'variety': 3, 'exciting': 1, 'level': 1, 'head': 1, 'rational': 1, 'approach': 1, 'problem': 1, 'combined': 1, 'passion': 1, 'innovative': 1, 'fresh': 1, 'led': 1, 'portfolio': 1, 'impressive': 1, 'strong': 1, 'communicator': 1, 'ability': 1, 'convey': 1, 'clearly': 1, 'emphasis': 1, 'client': 2, 'satisfaction': 1, 'technical': 1, 'personal': 2, 'communication': 1, 'organization': 1, 'team': 6, 'player': 1, 'creativity': 1, 'present': 1, 'working': 1, 'extensive': 1, 'theme': 2, 'versed': 2, 'time': 1, 'education': 1, 'master': 1, 'computer': 1, 'application': 1, 'project': 1, 'title': 4, 'technology': 4, 'social': 6, 'media': 4, 'description': 4, 'kind': 1, 'category': 1, 'premium': 1, 'underwear': 1, 'brand': 1, 'platform': 1, 'providing': 1, 'super': 1, 'interface': 1, 'recurring': 1, 'payment': 2, 'module': 1, 'place': 2, 'hassle': 1, 'free': 1, 'month': 1, 'responsibility': 4, 'scratch': 2,

In [92]:
def summarized_sent(d):
    docx = nlp(d)
    word_frc = {}
    for word in docx:
        if word.text in words:
            if word.text not in stopwords:
                if word.text not in word_frc.keys():

                    word_frc[word.text] = 1
                else:
                    word_frc[word.text] += 1
    max_frec = max(word_frc.values())
    key_list = list(word_frc.keys())
    val_list = list(word_frc.values())
    position = val_list.index(max_frec)
    print(key_list[position])
    for word in word_frc.keys():
        word_frc[word] =(word_frc[word]/max_frec)
        sentences  = [ sent for sent in docx.sents]
        sentence_score = {}
        for sent in sentences:
            for word in sent:
                if word.text.lower() in word_frc.keys():
                    if len(sent.text.split(' ')) < 30:
                        if sent not in sentence_score.keys():
                            sentence_score[sent] = word_frc[word.text.lower()]
                        else:
                            sentence_score[sent] += word_frc[word.text.lower()]
    summarized_sentences = nlargest(5, sentence_score, key = sentence_score.get)
    final_sentence = [w.text for w in summarized_sentences]
    
    summary = ' '.join(final_sentence) 
    return summary

In [93]:
print(summarized_sent(sample[10]))
print(sample_cleaned[10])

NameError: name 'words' is not defined

In [171]:
sample_cleaned = []
for i in range(len(sample)):
    sample_cleaned.append(summarized_sent(sample[i]))
    
sample_cleaned

data
application
design
stack
web
stack
new
stack
application
stack
developer
project
supply


['skills data mining, data analysis, machine learning, python, r, matlab, sphinx, latex, mathematica,  maple, git, cvs, htcondor. \uf09f skills used data cleansing and data analysis using python, scala, r and spark. two years of working experience  in data analysis team of ligo scientific collaboration [$3m special breakthrough prize winner of  2016]. \uf09f implemented data mining and machine learning algorithms to describe and predict user  behavior on various retailer websites. objective data scientist with phd in physics and 1+ industrial experience.',
 '\uf0a7 team\xa0lead\xa0on\xa0full\xa0stack\xa0javascript\xa0online\xa0auto\xa0insurance\xa0quote\xa0application\xa0with\xa0 react/redux\xa0frontend\xa0and\xa0express/node\xa0backend. this\xa0free\xa0resume\xa0template\xa0is\xa0the\xa0copyright\xa0of\xa0qwikresume.com.\xa0usage\xa0guidelines robert\xa0smith full\xa0stack\xa0developer/web\xa0programmer phone:\xa0(0123)\xad456\xad789\xa0|\xa0email:\xa0info@qwikresume.com\xa0|\xa0websi

In [170]:
from gensim.summarization import summarize
words = set(nltk.corpus.words.words())

In [174]:
final_cleaned_1 = []
final_cleaned_2 = []
for d in sample_cleaned: 
    sent = " ".join(w for w in nltk.wordpunct_tokenize(d) if w.lower() in words or w.isalpha())
    final_cleaned_1.append(sent)
    
for d in sample:
    s= summarize(d, word_count=200)
    sent = " ".join(w for w in nltk.wordpunct_tokenize(s) if w.lower() in words or w.isalpha())
    final_cleaned_2.append(sent)
    
print(final_cleaned_1[0], '\n\n')

skills data mining data analysis machine learning python r matlab sphinx latex mathematica maple git cvs htcondor skills used data cleansing and data analysis using python scala r and spark two years of working experience in data analysis team of ligo scientific collaboration special breakthrough prize winner of implemented data mining and machine learning algorithms to describe and predict user behavior on various retailer websites objective data scientist with phd in physics and industrial experience 




In [169]:
final_cleaned_1 = []
final_cleaned_2 = []
for d in sample_cleaned: 
    sent = " ".join(w for w in nltk.word_tokenize(d) if w.lower() in words or w.isalpha())
    final_cleaned_1.append(sent)
    
for d in sample:
    s= summarize(d, word_count=200)
    sent = " ".join(w for w in nltk.word_tokenize(s) if w.lower() in words or w.isalpha())
    final_cleaned_2.append(sent)
    
print(final_cleaned_1, '\n\n')

['skills data mining data analysis machine learning python r matlab sphinx latex mathematica maple git cvs htcondor skills used data cleansing and data analysis using python scala r and spark two years of working experience in data analysis team of ligo scientific collaboration special breakthrough prize winner of implemented data mining and machine learning algorithms to describe and predict user behavior on various retailer websites objective data scientist with phd in physics and industrial experience', 'team lead on full stack javascript online auto insurance quote application with frontend and backend this free resume template is the copyright of usage guidelines robert smith full stack programmer phone email info website worked onsite at pivotal labs in san francisco with a team of pivotal employees architecting and starting development for quoting application used angular js as framework to create a single page application spa which can bind data to specific views and synchroniz

In [27]:
words = set(nltk.corpus.words.words())
result = " ".join(w for w in nltk.wordpunct_tokenize(final_cleaned_1[0]) if w.lower() in words or not w.isalpha())
result

'data mining data analysis machine learning python r sphinx latex maple git used data cleansing and data analysis python scala r and spark two of working experience in data analysis team of scientific collaboration special breakthrough prize winner of data mining and machine learning to describe and predict user behavior on various retailer objective data scientist with in physics and industrial experience certified in data analysis and machine learning work experience data scientist corporation data scientist corporation for data scientist smith phone i their quot predictive marketing quot process to be more data driven and profitable designed and applied statistical and mathematical for corporate analytics that were into the new process was able to hone in on more useful user that had a significant increase in conversion over ten of successful research experience in both theoretical and computational physics responsible for in the appropriate media and creation of supporting document

In [24]:
# import nltk 
# nltk.download('wordnet') 
# from nltk.stem import WordNetLemmatizer 
  
# # Create WordNetLemmatizer object 
# wnl = WordNetLemmatizer() 
# dok= []
# for words in final_cleaned_1[-2]:
#     dok.append(wnl(words))
# print('\n\n', dok)

In [28]:
from string import punctuation
job_1 = "We seek a talented Entry Level Front End Web Developer. The selected candidate will be required to update and maintain a number of WordPress site plugins and core files as well as backup and test changes. Additionally, they will be tasked with creating html/css base templates for new or existing sites from a design. Other tasks to include maintenance and edits to existing sites as needed. Self-motivated, self-starters are preferred for this positionEducation: Bachelor’s degree or in progress, or 1-3 years equivalent experience.QualificationsCreate HTML/CSS pages from a designUnderstanding of responsive layoutsFamiliarity with WordPressAppreciation for design aestheticsAbility to use Javascript for interactive page elements (JQuery or other frameworks)PHP skills a plus"
job_1 = " ".join(w.lower() for w in nltk.word_tokenize(job_1) if w.lower() in words or w.isalpha())
job_1

'we seek a talented entry level front end web developer the selected candidate will be required to update and maintain a number of wordpress site plugins and core files as well as backup and test changes additionally they will be tasked with creating base templates for new or existing sites from a design other tasks to include maintenance and edits to existing sites as needed are preferred for this positioneducation bachelor s degree or in progress or years equivalent pages from a designunderstanding of responsive layoutsfamiliarity with wordpressappreciation for design aestheticsability to use javascript for interactive page elements jquery or other frameworks php skills a plus'

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [30]:
txt = []
for i in range(len(sample)):
    text = [final_cleaned_1[i], job_1]
    txt.append(text) 
txt

[['skills data mining data analysis machine learning python r matlab sphinx latex mathematica maple git cvs htcondor skills used data cleansing and data analysis using python scala r and spark two years of working experience in data analysis team of ligo scientific collaboration special breakthrough prize winner of implemented data mining and machine learning algorithms to describe and predict user behavior on various retailer websites objective data scientist with phd in physics and industrial experience certified in data analysis and machine learning work experience data scientist abc corporation data scientist abc corporation maintained automated etl for reporting data scientist robert smith phone i revamped their quot predictive marketing quot process to be more data driven and profitable designed and applied statistical and mathematical methods for corporate analytics that were implemented into products the new process was able to hone in on more useful user segments that had a si

In [31]:
tfid_inst_1 = TfidfVectorizer(analyzer='word', ngram_range=(1, 3), min_df=0)
score = []
for i in range(len(sample)):
    tfid_matrix_1 = tfid_inst_1.fit_transform(txt[i])

    cosine_similarity = linear_kernel(tfid_matrix_1)

    score.append(cosine_similarity)
score

[array([[1.        , 0.10051102],
        [0.10051102, 1.        ]]),
 array([[1.        , 0.12110656],
        [0.12110656, 1.        ]]),
 array([[1.        , 0.10947168],
        [0.10947168, 1.        ]]),
 array([[1.        , 0.10364988],
        [0.10364988, 1.        ]]),
 array([[1.        , 0.12970014],
        [0.12970014, 1.        ]]),
 array([[1.        , 0.13503916],
        [0.13503916, 1.        ]]),
 array([[1.        , 0.10359449],
        [0.10359449, 1.        ]]),
 array([[1.        , 0.10087612],
        [0.10087612, 1.        ]]),
 array([[1.        , 0.11701344],
        [0.11701344, 1.        ]]),
 array([[1.        , 0.12143643],
        [0.12143643, 1.        ]]),
 array([[1.        , 0.09670106],
        [0.09670106, 1.        ]]),
 array([[1.        , 0.10132375],
        [0.10132375, 1.        ]]),
 array([[1.        , 0.10806888],
        [0.10806888, 1.        ]])]

In [36]:
sample[-3]

'\xa0 \xa0 \xa0 \xa0 \xa0 +91 120 4288752\xa0 \xa0 sales@ongraph.com\xa0 www.ongraph.com\xa0 \xa0 about me\xa0 \xa0 a highly experienced and\xa0 creative wordpress developer\xa0 with seven years experience in a\xa0 variety of exciting projects. a\xa0 level head and rational\xa0 approach to problem solving\xa0 combined with a passion for\xa0 innovative and fresh ideas has led\xa0 to a portfolio of impressive\xa0 website solutions.\xa0  strong communicator with the\xa0 ability to convey ideas clearly\xa0 with an emphasis on client\xa0 satisfaction.\xa0 \xa0         technical skills\xa0 \xa0 wordpress\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 php\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 mysql\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 html5\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 css\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 personal skills\xa0 \xa0 communication\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 organization\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 team player\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 creativity\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 sr.wordpress devel

In [32]:
txt_2 = []
for i in range(len(sample)):
    text_2 = [final_cleaned_2[i], job_1]
    txt_2.append(text_2) 

In [33]:
tfid_inst_2 = TfidfVectorizer(analyzer='word', ngram_range=(1, 3), min_df=0)
score_2 = []
for i in range(len(sample)):
    tfid_matrix_1 = tfid_inst_2.fit_transform(txt_2[i])

    cosine_similarity = linear_kernel(tfid_matrix_1)

    score_2.append(cosine_similarity)
score_2

[array([[1.        , 0.10222382],
        [0.10222382, 1.        ]]),
 array([[1.        , 0.08395666],
        [0.08395666, 1.        ]]),
 array([[1.        , 0.09731671],
        [0.09731671, 1.        ]]),
 array([[1.        , 0.10862389],
        [0.10862389, 1.        ]]),
 array([[1.        , 0.13429106],
        [0.13429106, 1.        ]]),
 array([[1.        , 0.12015537],
        [0.12015537, 1.        ]]),
 array([[1.        , 0.09049955],
        [0.09049955, 1.        ]]),
 array([[1.       , 0.0876356],
        [0.0876356, 1.       ]]),
 array([[1.        , 0.09824309],
        [0.09824309, 1.        ]]),
 array([[1.        , 0.12708966],
        [0.12708966, 1.        ]]),
 array([[1.       , 0.0772366],
        [0.0772366, 1.       ]]),
 array([[1.        , 0.08702345],
        [0.08702345, 1.        ]]),
 array([[1.        , 0.06258015],
        [0.06258015, 1.        ]])]

In [114]:
print((final_cleaned_1[-3]), '\n\n')
print(final_cleaned_2[-3])

role frontend and backend developer title karmony technology php mysql wordpress woocommerce paypal social media api description date role wordpress developer title memberslesbrown technology php mysql javascript description a highly experienced and creative wordpress developer with seven years experience in a variety of exciting projects title underwearnation technology php mysql wordpress woocommerce paypal social media api description team size role wordpress developer 


integrated google map api google analytics team size role frontend and backend developer title karmony technology php mysql wordpress woocommerce paypal social media api description this website provide a broader variety of needs than most rather than specializing in one style of training coaches shop it helps people find the style that works for them and offers coaches versed in a variety of fitness methodologies i worked on membership features shop schedule plugin and integrated social media api team size copyrig

In [30]:
docx = nlp(sample[-3])
word_frc = {}
for word in docx:
    if word.text not in stopwords:
         if word.text in words:
            if word.text not in word_frc.keys():
                word_frc[word.text] = 1
            else:
                word_frc[word.text] += 1
word_frc

{'highly': 1,
 'experienced': 1,
 'creative': 1,
 'developer': 8,
 'seven': 1,
 'experience': 6,
 'variety': 3,
 'exciting': 1,
 'level': 1,
 'head': 1,
 'rational': 1,
 'approach': 1,
 'problem': 1,
 'combined': 1,
 'passion': 1,
 'innovative': 1,
 'fresh': 1,
 'led': 1,
 'portfolio': 1,
 'impressive': 1,
 'strong': 1,
 'communicator': 1,
 'ability': 1,
 'convey': 1,
 'clearly': 1,
 'emphasis': 1,
 'client': 2,
 'satisfaction': 1,
 'technical': 1,
 'personal': 2,
 'communication': 1,
 'organization': 1,
 'team': 6,
 'player': 1,
 'creativity': 1,
 'present': 1,
 'working': 1,
 'extensive': 1,
 'theme': 2,
 'versed': 2,
 'time': 1,
 'education': 1,
 'master': 1,
 'computer': 1,
 'application': 1,
 'project': 1,
 'title': 4,
 'technology': 4,
 'social': 6,
 'media': 4,
 'description': 4,
 'kind': 1,
 'category': 1,
 'premium': 1,
 'underwear': 1,
 'brand': 1,
 'platform': 1,
 'providing': 1,
 'super': 1,
 'interface': 1,
 'recurring': 1,
 'payment': 2,
 'module': 1,
 'place': 2,
 'hassl

In [126]:
for word in stopwords:
    if (word=='the'):
        print('yes')

yes


In [235]:
import numpy as np
max_frec = max(word_frc.values())
for word in word_frc.keys():
        word_frc[word] =(word_frc[word]/max_frec)
d=word_frc.get('wordpress')
d

0.13829787234042545